### ISSUE TITLE
Can it show details about the fields

### ISSUE THREAD

**Issue by Misfit-John** [navneethg/jsonschemaviewer#1]
Hi, I am so happy to find your tool, it do save my life. But can it show more details about the fields? like the type ? It will be much more better.

**Comment by navneethg** [comment]
Glad it helped. It's currently an assembly of existing projects I found here on github. I badly needed an eagles eye view to explore a schema, hence quickly wired it up. Authoring a complicated schema right now, once done I'll get back to reworking on this to show more details about the fields etc... I'll keep the issue open :)

**Comment by navneethg** [comment]
This is the project I am using: https://github.com/jlblcc/json-schema-viewer. It is essentially the same UI but I didn't enable all those sidebars and legends. Btw, I am thinking of a total rewrite,.

**Comment by Misfit-John** [comment]
Yes, I know that repo. Just I don't know much about front end and js, so I am a bit confuse about how to make them show up. Another suggestion is that maybe you should mention that repo in your readme file, that will be better.

Anyway, this repo is much better because all I need to do is clone and open it. Great thanks.

**Comment by navneethg** [comment]
I have updated the README, and the visualization now shows types.

**Comment by Misfit-John** [comment]
Can't be more grateful.
